<!DOCTYPE thirdpartyvendor [
    <!ELEMENT thirdpartyvendor (user.full_name+,user.ID,user.user_name+,user.IBAN+,user.BIC+,user.user_bank_name+,user.phone_number?,waste_type?)>
    <!ELEMENT user.full_name (#PCDATA)>
    <!ELEMENT user.ID (#PCDATA)>
    <!ELEMENT user.user_name (#PCDATA)>
    <!ELEMENT user.IBAN (#PCDATA)>
    <!ELEMENT user.BIC (#PCDATA)>
    <!ELEMENT user.user_bank_name (#PCDATA)>
    <!ELEMENT user.phone_number (#PCDATA)>
    <!ELEMENT waste_type (#PCDATA)>
    <!ATTLIST thirdpartyvendor Address CDATA #REQUIRED>
]>
<?xmlversion = "1.0"?>
<thirdpartyvendor Address = "12ab">
    <user.full_name> Killmain Biodegradable Waste Centre </user.full_name>
    <user.ID> 1122 </user.ID>
    <user.user_name> KillmainBWC </user.user_name>
    <user.IBAN> IE64IRCE92050112345678 </user.IBAN>
    <user.BIC> IRCE92 </user.BIC>
    <user.user_bank_name> Irish Central Bank </user.user_bank_name>
    <user.phone_number> 012348762</user.phone_number>
    <waste_type> Biodegradable </waste_type>
</thirdpartyvendor>

<!-- <user>
</user> -->

<!-- <user.address> <Address idref="12ab"/> </user.address> -->

<!-- <thirdpartyvendor>
    <user.full_name> </user.full_name>
    <user.ID> </user.ID>
    <user.user_name> </user.user_name>
    <user.address> <Address idref=" "/> </user.address>
    <user.IBAN> </user.IBAN>
    <user.BIC> </user.BIC>
    <user.user_bank_name> </user.user_bank_name>
    <user.phone_number> </user.phone_number>
    <thirdpartyvendor.waste_type> </thirdpartyvendor.waste_type>
</thirdpartyvendor> -->
